version: '3'
services: 
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: root
    ports: 
      - 5432:5432
  backend:
    image:  grameaway/opn_backend
    depends_on: 
        - db
    expose: 
        - "5000" 
  lb: 
     image: grameaway/opn_loadbalancer
     ports:
       - 80:80
       - 443:443
     links:
       - backend